application:
  title: IdReports
  version: 0.0.1-SNAPSHOT

server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idReport_db?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
