application:
  title: IdReports
  version: 0.0.1-SNAPSHOT

server:
  servlet:
    context-path: /report
  port: 8080

keycloak:
  realm: idReports
  auth-server-url: http://localhost:8180
  ssl-required: external
  resource: idreports_backend
  use-resource-role-mappings: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idReport_db?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

