application:
  title: IdReports
  version: 0.0.1-SNAPSHOT

server:
  servlet:
    context-path: /report
  port: 9090

keycloak:
  realm: idreports
  auth-server-url: http://localhost:8081
  resource: springboot-idreports
  bearer-only: true
  use-resource-role-mappings: true
  ssl-required: none


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idReport_db?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

